version: "3.7"
services:
  a3p_redis:
    image: redis:5
    networks:
      a3p_network:
        aliases:
          - redis

  a3p_mongo:
    image: mongo:4.2
    volumes:
      - a3p_mongodata:/data/db
    networks:
      a3p_network:
        aliases:
          - mongo

  a3p_influxdb:
    image: influxdb:1.7
    volumes:
      - a3p_influxdbdata:/var/lib/influxdb
    networks:
      a3p_network:
        aliases:
          - influx

  a3p_services:
    build:
      context: ./../..
      dockerfile: docker/dockerfiles/backend_services/Dockerfile
    image: a3p_services
    networks:
      a3p_network:
        aliases:
          - services

  a3p_api:
    image: a3p_api
    depends_on:
      - a3p_mongo
      - a3p_influxdb
      - a3p_redis
      - a3p_services
    networks:
      a3p_network:

  a3p_frontend:
    image: a3p_frontend
    networks:
      a3p_network:

volumes:
  a3p_mongodata:
  a3p_influxdbdata:

networks:
   a3p_network:
     driver: bridge
