version: "3.7"
services:
  a3p_redis:
    image: redis:5
    ports:
      - 6379:6379

  a3p_mongo:
    image: mongo:4.2
    volumes:
      - a3p_mongodata:/data/db
    ports:
      - 27017:27017

  a3p_influxdb:
    image: influxdb:1.7
    volumes:
      - a3p_influxdbdata:/var/lib/influxdb
    ports:
      - 8086:8086

volumes:
  a3p_mongodata:
  a3p_influxdbdata:
