version: "3.7"
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    volumes:
      - a3p_mongodata:/data/db
    ports:
      - 27017:27017

  influxdb:
    image: influxdb
    volumes:
      - a3p_influxdbdata:/var/lib/influxdb
    ports:
      - 8086:8086

volumes:
  a3p_mongodata:
    name: a3p_mongodata

  a3p_influxdbdata:
    name: a3p_influxdbdata
